# -*- coding: utf-8 -*-
"""dist

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NI_Uejly8W48uuUAk8Uu-emq0kQHCUyA
"""

import numpy as np
from scipy.spatial import ConvexHull
from PyGEL3D import gel

def dist(hull, points):
    m = gel.Manifold()
    for s in hull.simplices:
        m.add_face(hull.points[s])

    dist = gel.MeshDistance(m)
    res = []
    for p in points:
        d = dist.signed_distance(p)
        if dist.ray_inside_test(p):
            if d > 0:
                d *= -1
        else:
            if d < 0:
                d *= -1
        res.append(d)
    return np.array(res)